In [9]:
import tensorflow as tf
x=tf.ones(shape=(2,1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


全1张量

### 常数张量和变量

In [10]:
x=tf.zeros(shape=(2,1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


全0张量

In [11]:
x=tf.random.normal(shape=(3,1),mean=0,stddev=1) # 从均值为0，标准差为1的正态分布中抽取随机张量
print(x)
y=tf.random.uniform(shape=(3,1),minval=0,maxval=1) #从0-1的均匀分布中抽取随机张量
print(y)

tf.Tensor(
[[-0.48103842]
 [-0.962853  ]
 [ 0.58641815]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[0.6175209 ]
 [0.9783952 ]
 [0.56153595]], shape=(3, 1), dtype=float32)


Numpy数组和TensorFlow张量之间的一个主要区别是TensorFlow张量是不可赋值的，但是Numpy数组可以赋值

In [12]:
import numpy as np
x=np.ones(shape=(2,2))
x[0,0]=0 #可赋值
print(x)

[[0. 1.]
 [1. 1.]]


In [13]:
v=tf.Variable(initial_value=tf.random.normal(shape=(3,1))) # TensorFlow变量
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.58529013],
       [-0.15528397],
       [-0.14135493]], dtype=float32)>


In [14]:
v.assign(tf.ones((3,1)))
print(v)
v[0,0].assign(3)
print(v)
v.assign_add(tf.ones((3,1)))
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>


使用GradientTape检索任意可微表达式相对于其输入的梯度

In [18]:
input_var =tf.Variable(initial_value=3)
with tf.GradientTape() as tape:
    result= tf.square(input_var)
gradient=tape.gradient(result,input_var)
print(gradient)

None


利用嵌套的梯度带计算二阶梯度

In [ ]:
time=tf.Variable(0)
with tf.GradientTape() as outertape:
    with tf.GradientTape()  